# Generated by Django 5.1.1 on 2024-09-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Ultimo Nome'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone1',
            field=models.CharField(max_length=11, verbose_name='Telefone 1'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone2',
            field=models.CharField(max_length=11, verbose_name='Telefone 2'),
        ),
    ]
