# Generated by Django 5.1.1 on 2024-09-22 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_cpf_alter_customers_firstname_and_more'),
        ('orders', '0003_remove_orders_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.customers', verbose_name='Cliente'),
        ),
    ]
