# Generated by Django 5.1.1 on 2024-09-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_custumer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='custumer',
            new_name='customer',
        ),
    ]
