# Generated by Django 5.1.1 on 2024-09-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_cpf_alter_customers_firstname_and_more'),
        ('orders', '0008_customer_alter_orders_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Cliente',
        ),
    ]
