# Generated by Django 5.1.1 on 2024-09-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
