# Generated by Django 5.1.1 on 2024-09-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orders_valor_delete_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=10, null=True, verbose_name='Valor'),
        ),
    ]
