# Generated by Django 5.1.1 on 2024-09-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orders_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=10, verbose_name='Valor'),
        ),
    ]
